#!/bin/sh
#
# desc: simple script to run all auto commands
#
####

# defines needed for OpenBSD
AUTOMAKE_VERSION=1.15;export AUTOMAKE_VERSION
AUTOCONF_VERSION=2.69;export AUTOCONF_VERSION

if [ ! -d config ]; then
 mkdir config
fi

aclocal
automake --gnu --add-missing
autoconf
autoheader

