#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          passivedns
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Passive DNS collector
# Description:       This is a network (security) tool designed to 
#                    collect DNS information for troubleshooting or
#                    security related work
### END INIT INFO

NAME=passivedns
PIDFILE=/var/run/passivedns.pid
DAEMON=/usr/bin/$NAME
ARGS="-i eth0 -D"

# Source default configs.
if [ -r /etc/default/passivedns ]; then
  . /etc/default/passivedns
fi

# See how we were called.
case "$1" in
  start)
        echo -n "Starting $NAME ..."
        $DAEMON $ARGS > /dev/null 2>&1
        echo " done."
        ;;
  stop)
        echo -n "Stopping $NAME ..."
        start-stop-daemon --oknodo --stop --quiet --pidfile=$PIDFILE --exec $DAEMON
        rm -f $PIDFILE > /dev/null 2>&1
        echo " done."
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            ps -p $PID > /dev/null 2>&1
            RC=$?
            if [ "$RC" == "0" ]; then
                echo "PassiveDNS is running with PID $PID..."
            else
                echo "PassiveDNS is not running..."
            fi
        else
            echo "PassiveDNS is not running..."
        fi
        ;;
  force-reload)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
esac

exit 0

